import './globals.css'
import type { Metadata } from 'next'
import Navbar from './navbar/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
         <div>Copyright 2023 by Jonathan Poteet</div>
      </body>
    </html>
  )
}
